import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { dispatchLaunchAgent, menuLaunchAgent, serviceLaunchAgent } from "../src/install/macos.js";

test("macOS install configuration is loopback-local, durable, reversible, and path-safe", () => {
  const input = { node: "/opt/homebrew/bin/node", repository: "/Users/Test & Dev/roundhouse", home: "/Users/Test & Dev" };
  const service = serviceLaunchAgent(input);
  const dispatch = dispatchLaunchAgent({ home: input.home });
  const menu = menuLaunchAgent({ executable: "/Applications/Roundhouse Menu.app/Contents/MacOS/RoundhouseMenu", home: input.home });
  assert.match(service, /io\.roundhouse\.service/);
  assert.match(service, /Application Support\/Roundhouse\/projects\.yaml/);
  assert.match(service, /scripts\/macos\/service-wrapper\.sh/);
  assert.doesNotMatch(service, /DATABASE_URL/);
  assert.match(service, /Test &amp; Dev/);
  assert.match(menu, /io\.roundhouse\.menu/);
  assert.match(dispatch, /io\.roundhouse\.dispatch/);
  assert.match(dispatch, /api\/worker\/tick/);
  assert.match(dispatch, /StartInterval/);
  assert.doesNotMatch(dispatch, /git\/roundhouse|src\/cli\.js|dispatch-once/);
});

test("menu bar companion remains a designed native HTTP control room with service controls", () => {
  const source = fs.readFileSync("macos/RoundhouseMenu/main.swift", "utf8");
  assert.match(source, /import AppKit/);
  assert.match(source, /https:\/\/roundhouse\.ryan\.green/);
  assert.match(source, /api\/local-snapshot/);
  assert.doesNotMatch(source, /api\/overview|api\/notifications/);
  assert.match(source, /notificationCursor/);
  assert.match(source, /import SwiftUI/);
  assert.match(source, /struct DashboardView: View/);
  assert.match(source, /NSPopover/);
  assert.match(source, /Open dashboard/);
  assert.match(source, /Start local service/);
  assert.match(source, /Stop local service/);
  assert.match(source, /Restart local service/);
  assert.match(source, /Local service is unavailable/);
  assert.match(source, /projectionRevision/);
  assert.match(source, /snapshotError/);
  assert.match(source, /Priority work/);
  assert.match(source, /status-light/);
  assert.match(source, /isTemplate = true/);
  assert.ok(fs.existsSync("macos/RoundhouseMenu/status-light.svg"));
  assert.ok(fs.existsSync("macos/RoundhouseMenu/status-dark.svg"));
  const menuBuild = fs.readFileSync("scripts/macos/menu-bar.sh", "utf8");
  assert.match(menuBuild, /Contents\/Resources/);
  assert.match(menuBuild, /status-light\.svg/);
  assert.match(menuBuild, /status-dark\.svg/);
  assert.doesNotMatch(source, /Electron|terminal output/i);
});

test("installer reports success only after direct engine health and never reinstalls the retired browser", () => {
  const installer = fs.readFileSync("scripts/macos/install.sh", "utf8");
  const service = fs.readFileSync("scripts/macos/service.sh", "utf8");
  assert.match(installer, /app_health/);
  assert.match(installer, /wait_for_health "app service"/);
  assert.doesNotMatch(installer, /front-door|http:\/\/roundhouse/);
  assert.match(installer, /Initial user service bootstrap failed/);
  assert.match(installer, /io\.roundhouse\.dispatch\.plist/);
  assert.match(installer, /Initial dispatcher bootstrap failed/);
  assert.match(installer, /install\|repair\|smoke/);
  assert.match(service, /repair\)/);
  assert.match(service, /smoke\)/);
  const wrapper = fs.readFileSync("scripts/macos/service-wrapper.sh", "utf8");
  assert.match(wrapper, /relay\.env/);
  assert.match(wrapper, /ROUNDHOUSE_STORAGE_MODE="local"/);
  assert.match(wrapper, /400\|600/);
  assert.match(wrapper, /unset DATABASE_URL DATABASE_URL_UNPOOLED NEON_BRANCH/);
  const menuBuild = fs.readFileSync("scripts/macos/menu-bar.sh", "utf8");
  assert.match(menuBuild, /codesign --verify --deep --strict/);
  assert.match(menuBuild, /bootout/);
  assert.match(menuBuild, /bootstrap/);
  assert.match(menuBuild, /menu-rollbacks/);
  assert.equal(fs.existsSync("src/server/front-door.js"), false);
  assert.equal(fs.existsSync("src/web/index.html"), false);
  assert.equal(fs.existsSync("src/mcp/http-server.js"), false);
});
