import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { Store } from "../src/workflow/store.js";
import { pickup, updates, acknowledge } from "../src/workflow/notion-bridge.js";
import { notionInput, statusView } from "../src/workflow/cli.js";

test("Notion pickup is opt-in, UUID-idempotent and sync receipts reject stale state", (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "roundhouse-bridge-"));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const store = new Store(dir);
  const source = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
  const page = { id: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", data_source_id: source, properties: { Item: "Test", Project: "Roundhouse", "Workflow State": "Depot" } };
  const batch = { data_source_id: source, pages: [page] };
  const projects = [{ id: "roundhouse", name: "Roundhouse" }];
  assert.equal(pickup(store, batch, projects, notionInput)[0].duplicate, false);
  page.properties.Item = "An edit must not execute twice";
  assert.equal(pickup(store, batch, projects, notionInput)[0].duplicate, true);
  const first = updates(store.read(), statusView)[0];
  assert.equal(first.properties["Workflow State"], "Depot");
  store.change((data) => store.move(data, data.items[first.item_id], "Decision", "Interpreting"));
  assert.throws(() => acknowledge(store, first, statusView), /Stale/);
  const next = updates(store.read(), statusView)[0];
  acknowledge(store, next, statusView);
  assert.deepEqual(updates(store.read(), statusView), []);
  page.id = "cccccccccccccccccccccccccccccccc";
  page.properties["Workflow State"] = "Review";
  assert.equal(pickup(store, batch, projects, notionInput)[0].skipped, true);
  page.properties["Workflow State"] = "Depot";
  page.properties["Roundhouse Job ID"] = "another-owner";
  assert.throws(() => pickup(store, batch, projects, notionInput), /owned/);
});
